version: '3'
services:
  shyftgeth:
    build:
      context: $PWD 
      dockerfile: ./Dockerfile
    image: tim/latestgeth
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30301:30301"
      - "30301:30301/udp"
      - "30303:30303"
      - "30303:30303/udp"
      - "30304:30304"
      - "31333:31333"
      - "31333:31333/udp"
      - "8081:8081"
    volumes:
      - ./shyftData/:/go-empyrean/shyftData/
      - ./shyft-files/:/go-empyrean/shyft-files/
    working_dir: /go-empyrean
    depends_on: 
      - pg
    networks:
      - shyftnet
    command: >
      sh -c 'cd /go-empyrean &&
            ./shyft-files/wait-for.sh pg:5432 &&
            DBENV=docker export DBENV &&
            ./shyft-files/shyft-cli/initShyftGeth.sh &&
            ./shyft-files/shyft-cli/startShyftGeth.sh'
  pg:
    build: 
      context: $PWD
      dockerfile: docker/development/pg/Dockerfile
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "8001:5432"
    networks:
      - shyftnet
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
  shyft_block_api:
    build:
      context: $PWD 
      dockerfile: docker/development/shyftApi/Dockerfile
    # volumes:
    #   - ./shyftBlockExplorerApi:/go/src/github.com/ShyftNetwork/go-empyrean/shyftBlockExplorerApi
    working_dir: /go/src/github.com/ShyftNetwork/go-empyrean/shyftBlockExplorerApi
    ports:
      - "8080:8080"
    depends_on:
      - pg
    networks:
      - shyftnet
    command: >
      sh -c '
            pwd && govendor remove github.com/ShyftNetwork/go-empyrean/crypto/secp256k1/^ && 
            govendor fetch github.com/ShyftNetwork/go-empyrean/crypto/secp256k1/^  && 
            /wait-for.sh pg:5432 &&
            DBENV=docker export DBENV &&
            go run -v *.go'
  shyft_block_ui:
    build:
      context: $PWD 
      dockerfile: docker/development/shyftUi/Dockerfile
      # volumes:
      #   - ./shyftBlockExplorerApi:/go/src/github.com/ShyftNetwork/go-empyrean/shyftBlockExplorerApi
    ports:
      - "3000:3000"
    depends_on:
      - shyft_block_api
    networks:
      - shyftnet
networks:
  shyftnet:
    driver: bridge
  

